import type {
  ActivityRequirement,
  ActivityTrainingYear,
  ActivityTranscriptEntry,
} from "./activity-transcript";

export const activityTranscriptProfile = {
  memberId: "วภท-2568-001",
  programName: "หลักสูตรวุฒิบัตร สาขาเภสัชบำบัด",
  currentTrainingYear: 2 as ActivityTrainingYear,
};

export const activityTranscriptRequirements: ActivityRequirement[] = [
  {
    id: "y1-seminar",
    trainingYear: 1,
    category: "seminar",
    label: "การนำเสนอสัมมนา",
    description: "นำเสนอหัวข้อวิชาการตามแผนการฝึกอบรมปี 1",
    icon: "co_present",
    targetCount: 1,
    unit: "ครั้ง",
  },
  {
    id: "y1-journal-club",
    trainingYear: 1,
    category: "journal_club",
    label: "Journal Club",
    description: "วิเคราะห์และนำเสนอบทความวิชาการ",
    icon: "library_books",
    targetCount: 3,
    unit: "ครั้ง",
  },
  {
    id: "y1-case-presentation",
    trainingYear: 1,
    category: "case_presentation",
    label: "การนำเสนอกรณีศึกษา",
    description: "นำเสนอกรณีศึกษาจากการฝึกปฏิบัติงาน",
    icon: "clinical_notes",
    targetCount: 3,
    unit: "ครั้ง",
  },
  {
    id: "y1-teaching",
    trainingYear: 1,
    category: "teaching_supervision",
    label: "สอนหรือดูแลการฝึกปฏิบัติงาน",
    description: "เอกสารหลักสูตรกำหนดว่าต้องมี แต่ไม่ได้ระบุจำนวนขั้นต่ำ",
    icon: "school",
    unit: "รายการ",
  },
  {
    id: "y2-seminar",
    trainingYear: 2,
    category: "seminar",
    label: "การนำเสนอสัมมนา",
    description: "นำเสนอหัวข้อวิชาการอย่างน้อยปีละ 1 ครั้ง",
    icon: "co_present",
    targetCount: 1,
    unit: "ครั้ง",
  },
  {
    id: "y2-journal-club",
    trainingYear: 2,
    category: "journal_club",
    label: "Journal Club",
    description: "วิเคราะห์และนำเสนอบทความวิชาการอย่างน้อยปีละ 6 ครั้ง",
    icon: "library_books",
    targetCount: 6,
    unit: "ครั้ง",
  },
  {
    id: "y2-case-presentation",
    trainingYear: 2,
    category: "case_presentation",
    label: "การนำเสนอกรณีศึกษา",
    description: "นำเสนอกรณีศึกษาจากการฝึกเฉพาะทางอย่างน้อยปีละ 6 ครั้ง",
    icon: "clinical_notes",
    targetCount: 6,
    unit: "ครั้ง",
  },
  {
    id: "y2-domestic-publication",
    trainingYear: 2,
    category: "domestic_publication",
    label: "ผลงานตีพิมพ์ในประเทศ",
    description: "มีผลงานตีพิมพ์ในวารสารภายในประเทศ",
    icon: "article",
    targetCount: 1,
    unit: "เรื่อง",
  },
  {
    id: "y2-teaching",
    trainingYear: 2,
    category: "teaching_supervision",
    label: "สอนและดูแลการฝึกปฏิบัติงาน",
    description: "ดูแลนิสิตเภสัชศาสตร์และผู้เข้ารับการอบรมปี 1 โดยไม่ระบุจำนวนขั้นต่ำ",
    icon: "school",
    unit: "รายการ",
  },
  {
    id: "y3-seminar",
    trainingYear: 3,
    category: "seminar",
    label: "การนำเสนอสัมมนา",
    description: "นำเสนอหัวข้อวิชาการอย่างน้อยปีละ 1 ครั้ง",
    icon: "co_present",
    targetCount: 1,
    unit: "ครั้ง",
  },
  {
    id: "y3-journal-club",
    trainingYear: 3,
    category: "journal_club",
    label: "Journal Club",
    description: "วิเคราะห์และนำเสนอบทความวิชาการอย่างน้อยปีละ 6 ครั้ง",
    icon: "library_books",
    targetCount: 6,
    unit: "ครั้ง",
  },
  {
    id: "y3-case-presentation",
    trainingYear: 3,
    category: "case_presentation",
    label: "การนำเสนอกรณีศึกษา",
    description: "นำเสนอกรณีศึกษาจากการฝึกเฉพาะทางอย่างน้อยปีละ 6 ครั้ง",
    icon: "clinical_notes",
    targetCount: 6,
    unit: "ครั้ง",
  },
  {
    id: "y3-professional-project",
    trainingYear: 3,
    category: "professional_project",
    label: "Professional Project",
    description: "จัดทำโครงงานด้านวิชาชีพ",
    icon: "assignment",
    targetCount: 1,
    unit: "โครงงาน",
  },
  {
    id: "y3-practice-improvement",
    trainingYear: 3,
    category: "practice_improvement",
    label: "DUE / Critical Pathway / Disease Management",
    description: "จัดทำงานพัฒนาการใช้ยาหรือระบบดูแลผู้ป่วยตามที่หลักสูตรกำหนด",
    icon: "account_tree",
    targetCount: 1,
    unit: "เรื่อง",
  },
  {
    id: "y3-international-publication",
    trainingYear: 3,
    category: "international_publication",
    label: "ผลงานตีพิมพ์หรือผลงานที่ได้รับรอง",
    description: "ตีพิมพ์ในฐานข้อมูลสากลหรือได้รับรองจากคณะกรรมการบริหารวิทยาลัย",
    icon: "public",
    targetCount: 1,
    unit: "เรื่อง",
  },
  {
    id: "y3-teaching",
    trainingYear: 3,
    category: "teaching_supervision",
    label: "สอนและดูแลการฝึกปฏิบัติงาน",
    description: "ดูแลนิสิตเภสัชศาสตร์และผู้เข้ารับการอบรมปี 1–2 โดยไม่ระบุจำนวนขั้นต่ำ",
    icon: "school",
    unit: "รายการ",
  },
  {
    id: "y4-seminar",
    trainingYear: 4,
    category: "seminar",
    label: "การนำเสนอสัมมนา",
    description: "นำเสนอหัวข้อวิชาการอย่างน้อยปีละ 1 ครั้ง",
    icon: "co_present",
    targetCount: 1,
    unit: "ครั้ง",
  },
  {
    id: "y4-journal-club",
    trainingYear: 4,
    category: "journal_club",
    label: "Journal Club",
    description: "วิเคราะห์และนำเสนอบทความวิชาการอย่างน้อยปีละ 6 ครั้ง",
    icon: "library_books",
    targetCount: 6,
    unit: "ครั้ง",
  },
  {
    id: "y4-case-presentation",
    trainingYear: 4,
    category: "case_presentation",
    label: "การนำเสนอกรณีศึกษา",
    description: "นำเสนอกรณีศึกษาจากการฝึกวิจัยอย่างน้อยปีละ 6 ครั้ง",
    icon: "clinical_notes",
    targetCount: 6,
    unit: "ครั้ง",
  },
  {
    id: "y4-international-publication",
    trainingYear: 4,
    category: "international_publication",
    label: "บทความวิจัยภาษาอังกฤษ",
    description: "มีบทความวิจัยภาษาอังกฤษที่เป็นผู้นิพนธ์ชื่อแรกและตีพิมพ์ในวารสารที่อยู่ในฐานข้อมูลสากล",
    icon: "public",
    targetCount: 1,
    unit: "เรื่อง",
  },
  {
    id: "y4-teaching",
    trainingYear: 4,
    category: "teaching_supervision",
    label: "สอนและดูแลการฝึกอบรม",
    description: "ดูแลนิสิตเภสัชศาสตร์และผู้เข้ารับการอบรมปี 1–3 โดยไม่ระบุจำนวนขั้นต่ำ",
    icon: "school",
    unit: "รายการ",
  },
];

function verified(
  verifiedAt: string,
  evidenceUrl?: string,
  note?: string,
) {
  return {
    status: "verified" as const,
    verifiedBy: "อ.ภญ. กาญจนา ศรีสุข",
    verifiedAt,
    evidenceUrl,
    note,
  };
}

export const activityTranscriptEntries: ActivityTranscriptEntry[] = [
  {
    id: "activity-y1-seminar-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 1,
    academicYear: "2568",
    requirementId: "y1-seminar",
    category: "seminar",
    title: "การใช้ยาต้านการแข็งตัวของเลือดในผู้ป่วยสูงอายุ",
    activityDate: "2025-08-18",
    institution: "คณะเภสัชศาสตร์ มหาวิทยาลัยมหิดล",
    role: "ผู้นำเสนอ",
    description: "สัมมนาการประเมินความเหมาะสมและการติดตามความปลอดภัยของยาต้านการแข็งตัวของเลือด",
    source: "college_checkin",
    evidence: [
      { id: "e-y1-s-1", name: "แบบรับรองการนำเสนอสัมมนา", kind: "presentation" },
    ],
    verification: verified("2025-08-20"),
  },
  ...[
    ["01", "การประเมินประสิทธิผลของ SGLT2 inhibitors ในภาวะหัวใจล้มเหลว", "2025-09-12"],
    ["02", "การใช้ยาปฏิชีวนะอย่างสมเหตุผลในผู้ป่วยติดเชื้อทางเดินหายใจ", "2025-11-07"],
    ["03", "การติดตามความปลอดภัยของยาชีววัตถุในโรคข้ออักเสบ", "2026-01-16"],
  ].map(([sequence, title, activityDate]) => ({
    id: `activity-y1-journal-${sequence}`,
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 1 as const,
    academicYear: "2568",
    requirementId: "y1-journal-club",
    category: "journal_club" as const,
    title,
    activityDate,
    institution: "คณะเภสัชศาสตร์ มหาวิทยาลัยมหิดล",
    role: "ผู้นำเสนอ",
    description: "วิเคราะห์ระเบียบวิธีวิจัย ผลลัพธ์ และการประยุกต์ใช้หลักฐานกับการบริบาลผู้ป่วย",
    source: "college_checkin" as const,
    evidence: [
      { id: `e-y1-j-${sequence}`, name: `แบบประเมิน Journal Club ครั้งที่ ${Number(sequence)}`, kind: "presentation" as const },
    ],
    verification: verified(activityDate),
  })),
  ...[
    ["01", "ผู้ป่วยหัวใจล้มเหลวที่มีการทำงานของไตลดลง", "2025-10-03"],
    ["02", "ผู้ป่วยเบาหวานที่เกิดภาวะน้ำตาลในเลือดต่ำซ้ำ", "2025-12-19"],
    ["03", "ผู้ป่วยติดเชื้อในกระแสเลือดและการปรับขนาดยา", "2026-02-13"],
  ].map(([sequence, title, activityDate]) => ({
    id: `activity-y1-case-${sequence}`,
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 1 as const,
    academicYear: "2568",
    requirementId: "y1-case-presentation",
    category: "case_presentation" as const,
    title,
    activityDate,
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้นำเสนอกรณีศึกษา",
    description: "สรุปปัญหาที่เกี่ยวกับยา แผนการบริบาล และผลการติดตามผู้ป่วย",
    source: "college_checkin" as const,
    evidence: [
      { id: `e-y1-c-${sequence}`, name: `แบบประเมินกรณีศึกษา ครั้งที่ ${Number(sequence)}`, kind: "report" as const },
    ],
    verification: verified(activityDate),
  })),
  {
    id: "activity-y1-teaching-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 1,
    academicYear: "2568",
    requirementId: "y1-teaching",
    category: "teaching_supervision",
    title: "ดูแลนิสิตฝึกปฏิบัติงานบนหอผู้ป่วยอายุรกรรม",
    activityDate: "2026-03-06",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้ช่วยดูแลการฝึกปฏิบัติงาน",
    description: "ร่วมสอนการทบทวนรายการยาและให้ข้อเสนอแนะการวางแผนติดตามผู้ป่วย",
    source: "system",
    evidence: [
      { id: "e-y1-t-1", name: "หนังสือรับรองการดูแลนิสิต", kind: "certificate" },
    ],
    verification: verified("2026-03-10"),
  },
  {
    id: "activity-y2-seminar-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-seminar",
    category: "seminar",
    title: "การปรับการรักษาด้วยยาในผู้ป่วยโรคไตเรื้อรัง",
    activityDate: "2026-08-21",
    institution: "คณะเภสัชศาสตร์ มหาวิทยาลัยมหิดล",
    role: "ผู้นำเสนอ",
    description: "ทบทวนแนวทางการรักษาและการปรับขนาดยาตามการทำงานของไต",
    source: "college_checkin",
    evidence: [
      { id: "e-y2-s-1", name: "แบบประเมิน Seminar ปี 2", kind: "presentation" },
    ],
    verification: verified("2026-08-24"),
  },
  {
    id: "activity-y2-journal-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-journal-club",
    category: "journal_club",
    title: "Early vasopressor use in septic shock",
    activityDate: "2026-06-12",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้นำเสนอ",
    description: "ประเมินคุณภาพหลักฐานและความเหมาะสมต่อการใช้ในผู้ป่วยภาวะวิกฤติ",
    source: "college_checkin",
    evidence: [
      { id: "e-y2-j-1", name: "แบบประเมิน Journal Club ครั้งที่ 1", kind: "presentation" },
    ],
    verification: verified("2026-06-15"),
  },
  {
    id: "activity-y2-journal-02",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-journal-club",
    category: "journal_club",
    title: "Oral anticoagulants in patients with atrial fibrillation",
    activityDate: "2026-07-17",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้นำเสนอ",
    description: "เปรียบเทียบประสิทธิผลและความปลอดภัยของยาต้านการแข็งตัวของเลือด",
    source: "college_checkin",
    evidence: [
      { id: "e-y2-j-2", name: "แบบประเมิน Journal Club ครั้งที่ 2", kind: "presentation" },
    ],
    verification: verified("2026-07-20"),
  },
  {
    id: "activity-y2-journal-03",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-journal-club",
    category: "journal_club",
    title: "Precision dosing of vancomycin using AUC-guided monitoring",
    activityDate: "2026-09-04",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้นำเสนอ",
    description: "ทบทวนการติดตามระดับยาและการประยุกต์ใช้ AUC ในเวชปฏิบัติ",
    source: "student",
    evidence: [
      { id: "e-y2-j-3", name: "สไลด์และแบบลงชื่อผู้เข้าร่วม", kind: "attendance" },
    ],
    verification: {
      status: "pending",
      note: "รออาจารย์ผู้ควบคุมการฝึกยืนยันผลการนำเสนอ",
    },
  },
  {
    id: "activity-y2-case-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-case-presentation",
    category: "case_presentation",
    title: "ผู้ป่วยปอดอักเสบร่วมกับภาวะไตบาดเจ็บเฉียบพลัน",
    activityDate: "2026-06-26",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้นำเสนอกรณีศึกษา",
    description: "วิเคราะห์การเลือกยา ปรับขนาดยา และติดตามผลการรักษา",
    source: "college_checkin",
    evidence: [
      { id: "e-y2-c-1", name: "รายงานกรณีศึกษา ครั้งที่ 1", kind: "report" },
    ],
    verification: verified("2026-06-29"),
  },
  {
    id: "activity-y2-case-02",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-case-presentation",
    category: "case_presentation",
    title: "ผู้ป่วยหัวใจเต้นผิดจังหวะที่มีความเสี่ยงเลือดออก",
    activityDate: "2026-08-07",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้นำเสนอกรณีศึกษา",
    description: "ประเมินสมดุลระหว่างประโยชน์และความเสี่ยงของยาต้านการแข็งตัวของเลือด",
    source: "college_checkin",
    evidence: [
      { id: "e-y2-c-2", name: "รายงานกรณีศึกษา ครั้งที่ 2", kind: "report" },
    ],
    verification: verified("2026-08-10"),
  },
  {
    id: "activity-y2-case-03",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-case-presentation",
    category: "case_presentation",
    title: "ผู้ป่วยติดเชื้อดื้อยาที่ได้รับยาหลายชนิด",
    activityDate: "2026-09-11",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้จัดทำรายงาน",
    description: "บันทึกปัญหาการใช้ยาและแนวทางติดตามอาการไม่พึงประสงค์",
    source: "student",
    evidence: [
      { id: "e-y2-c-3", name: "ร่างรายงานกรณีศึกษา", kind: "report" },
    ],
    verification: {
      status: "self_declared",
      note: "บันทึกโดยผู้เรียนและยังไม่มีผู้ตรวจรับรอง",
    },
  },
  {
    id: "activity-y2-case-04",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-case-presentation",
    category: "case_presentation",
    title: "ผู้ป่วยเบาหวานที่มีข้อมูลติดตามไม่ครบถ้วน",
    activityDate: "2026-05-22",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้จัดทำรายงาน",
    description: "รายการตัวอย่างสำหรับแสดงสถานะที่ต้องแก้ไขข้อมูลก่อนรับรอง",
    source: "student",
    evidence: [],
    verification: {
      status: "rejected",
      verifiedBy: "อ.ภญ. กาญจนา ศรีสุข",
      verifiedAt: "2026-05-25",
      note: "กรุณาเพิ่มผลตรวจทางห้องปฏิบัติการและแผนติดตามผู้ป่วย",
    },
  },
  {
    id: "activity-y2-publication-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-domestic-publication",
    category: "domestic_publication",
    title: "บทบาทเภสัชกรในการติดตามการใช้ยาต้านจุลชีพ",
    activityDate: "2026-09-02",
    institution: "คณะเภสัชศาสตร์ มหาวิทยาลัยมหิดล",
    role: "ผู้เขียนร่วม",
    description: "บทความวิชาการฉบับร่างสำหรับส่งวารสารภายในประเทศ",
    source: "student",
    evidence: [
      { id: "e-y2-p-1", name: "ต้นฉบับบทความและหนังสือตอบรับ", kind: "publication" },
    ],
    verification: {
      status: "pending",
      note: "รอตรวจสอบหนังสือตอบรับจากวารสาร",
    },
  },
  {
    id: "activity-y2-teaching-01",
    memberId: activityTranscriptProfile.memberId,
    trainingYear: 2,
    academicYear: "2569",
    requirementId: "y2-teaching",
    category: "teaching_supervision",
    title: "ร่วมดูแลการทบทวนรายการยาของผู้เข้ารับการอบรมปี 1",
    activityDate: "2026-08-28",
    institution: "โรงพยาบาลศิริราช",
    role: "ผู้ช่วยสอน",
    description: "ให้คำแนะนำการเก็บข้อมูลผู้ป่วยและการระบุปัญหาที่เกี่ยวข้องกับยา",
    source: "student",
    evidence: [
      { id: "e-y2-t-1", name: "แบบรับรองการช่วยสอน", kind: "certificate" },
    ],
    verification: {
      status: "pending",
      note: "รออาจารย์ประจำแหล่งฝึกยืนยัน",
    },
  },
];
